backend/peer_api/config/routes.rb
Rails.application.routes.draw do
  resources :text_memories
  resources :pictures
  resources :users

end

backend/peer_api/app/models/picture.rb
class Picture < ActiveRecord::Base
  belongs_to :user
end

backend/peer_api/app/models/text_memory.rb
class TextMemory < ActiveRecord::Base
  belongs_to :user
end

backend/peer_api/app/models/user.rb
class User < ActiveRecord::Base
  
end

backend/peer_api/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

backend/peer_api/app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: [:show, :edit, :update, :destroy]

  # GET /pictures
  # GET /pictures.json
  def index
    @pictures = Picture.all
  end

  # GET /pictures/1
  # GET /pictures/1.json
  def show
  end

  # GET /pictures/new
  def new
    @picture = Picture.new
  end

  # GET /pictures/1/edit
  def edit
  end

  # POST /pictures
  # POST /pictures.json
  def create
    @picture = Picture.new(picture_params)

    respond_to do |format|
      if @picture.save
        format.html { redirect_to @picture, notice: 'Picture was successfully created.' }
        format.json { render :show, status: :created, location: @picture }
      else
        format.html { render :new }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pictures/1
  # PATCH/PUT /pictures/1.json
  def update
    respond_to do |format|
      if @picture.update(picture_params)
        format.html { redirect_to @picture, notice: 'Picture was successfully updated.' }
        format.json { render :show, status: :ok, location: @picture }
      else
        format.html { render :edit }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pictures/1
  # DELETE /pictures/1.json
  def destroy
    @picture.destroy
    respond_to do |format|
      format.html { redirect_to pictures_url, notice: 'Picture was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_picture
      @picture = Picture.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def picture_params
      params.require(:picture).permit(:url, :desc, :user_id)
    end
end

backend/peer_api/app/controllers/text_memories_controller.rb
class TextMemoriesController < ApplicationController
  before_action :set_text_memory, only: [:show, :edit, :update, :destroy]

  # GET /text_memories
  # GET /text_memories.json
  def index
    @text_memories = TextMemory.all
  end

  # GET /text_memories/1
  # GET /text_memories/1.json
  def show
  end

  # GET /text_memories/new
  def new
    @text_memory = TextMemory.new
  end

  # GET /text_memories/1/edit
  def edit
  end

  # POST /text_memories
  # POST /text_memories.json
  def create
    @text_memory = TextMemory.new(text_memory_params)

    respond_to do |format|
      if @text_memory.save
        format.html { redirect_to @text_memory, notice: 'Text memory was successfully created.' }
        format.json { render :show, status: :created, location: @text_memory }
      else
        format.html { render :new }
        format.json { render json: @text_memory.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /text_memories/1
  # PATCH/PUT /text_memories/1.json
  def update
    respond_to do |format|
      if @text_memory.update(text_memory_params)
        format.html { redirect_to @text_memory, notice: 'Text memory was successfully updated.' }
        format.json { render :show, status: :ok, location: @text_memory }
      else
        format.html { render :edit }
        format.json { render json: @text_memory.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /text_memories/1
  # DELETE /text_memories/1.json
  def destroy
    @text_memory.destroy
    respond_to do |format|
      format.html { redirect_to text_memories_url, notice: 'Text memory was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_text_memory
      @text_memory = TextMemory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def text_memory_params
      params.require(:text_memory).permit(:text, :user_id)
    end
end

backend/peer_api/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :dob)
    end
end

backend/peer_api/app/helpers/application_helper.rb
module ApplicationHelper
end

backend/peer_api/app/helpers/pictures_helper.rb
module PicturesHelper
end

backend/peer_api/app/helpers/text_memories_helper.rb
module TextMemoriesHelper
end

backend/peer_api/app/helpers/users_helper.rb
module UsersHelper
end

backend/peer_api/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PeerApi</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

backend/peer_api/app/views/pictures/_form.html.erb
<%= form_for(@picture) do |f| %>
  <% if @picture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@picture.errors.count, "error") %> prohibited this picture from being saved:</h2>

      <ul>
      <% @picture.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :desc %><br>
    <%= f.text_field :desc %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

backend/peer_api/app/views/pictures/edit.html.erb
<h1>Editing Picture</h1>

<%= render 'form' %>

<%= link_to 'Show', @picture %> |
<%= link_to 'Back', pictures_path %>

backend/peer_api/app/views/pictures/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Pictures</h1>

<table>
  <thead>
    <tr>
      <th>Url</th>
      <th>Desc</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pictures.each do |picture| %>
      <tr>
        <td><%= picture.url %></td>
        <td><%= picture.desc %></td>
        <td><%= picture.user %></td>
        <td><%= link_to 'Show', picture %></td>
        <td><%= link_to 'Edit', edit_picture_path(picture) %></td>
        <td><%= link_to 'Destroy', picture, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Picture', new_picture_path %>

backend/peer_api/app/views/pictures/new.html.erb
<h1>New Picture</h1>

<%= render 'form' %>

<%= link_to 'Back', pictures_path %>

backend/peer_api/app/views/pictures/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Url:</strong>
  <%= @picture.url %>
</p>

<p>
  <strong>Desc:</strong>
  <%= @picture.desc %>
</p>

<p>
  <strong>User:</strong>
  <%= @picture.user %>
</p>

<%= link_to 'Edit', edit_picture_path(@picture) %> |
<%= link_to 'Back', pictures_path %>

backend/peer_api/app/views/text_memories/_form.html.erb
<%= form_for(@text_memory) do |f| %>
  <% if @text_memory.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@text_memory.errors.count, "error") %> prohibited this text_memory from being saved:</h2>

      <ul>
      <% @text_memory.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :text %><br>
    <%= f.text_field :text %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

backend/peer_api/app/views/text_memories/edit.html.erb
<h1>Editing Text Memory</h1>

<%= render 'form' %>

<%= link_to 'Show', @text_memory %> |
<%= link_to 'Back', text_memories_path %>

backend/peer_api/app/views/text_memories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Text Memories</h1>

<table>
  <thead>
    <tr>
      <th>Text</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @text_memories.each do |text_memory| %>
      <tr>
        <td><%= text_memory.text %></td>
        <td><%= text_memory.user %></td>
        <td><%= link_to 'Show', text_memory %></td>
        <td><%= link_to 'Edit', edit_text_memory_path(text_memory) %></td>
        <td><%= link_to 'Destroy', text_memory, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Text memory', new_text_memory_path %>

backend/peer_api/app/views/text_memories/new.html.erb
<h1>New Text Memory</h1>

<%= render 'form' %>

<%= link_to 'Back', text_memories_path %>

backend/peer_api/app/views/text_memories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Text:</strong>
  <%= @text_memory.text %>
</p>

<p>
  <strong>User:</strong>
  <%= @text_memory.user %>
</p>

<%= link_to 'Edit', edit_text_memory_path(@text_memory) %> |
<%= link_to 'Back', text_memories_path %>

backend/peer_api/app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :dob %><br>
    <%= f.date_select :dob %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

backend/peer_api/app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

backend/peer_api/app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Dob</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.dob %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

backend/peer_api/app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

backend/peer_api/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Dob:</strong>
  <%= @user.dob %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>